config/routes.rb
Textprovider::Application.routes.draw do
  devise_for :admins
  devise_for :users

  root :to => 'home#index'

  resources :orders
  resources :items
  resources :pages

  match 'p/:slug' => 'pages#show'

  namespace :admin do
    root :to => 'dashboard#index'
    match "customers" => 'admins#customers'
    match "profile" => 'admin#profile'
    match "mail_preferences" => 'admin#mail_settings'
    match "save_mail_preferences" => 'admin#save_mail_settings'
    put "update_password" => 'admin#update_password'
    resources :dashboard
    resources :users
    resources :payments do 
      member do
        get 'complete'
      end
    end
    resources :orders do
      member do
        get 'close'
      end
    end
    resources :admins
    resources :items do
      member do
        get 'confirm'
        get 'conflict'
      end
      collection do
        get 'expired'
        get 'set_expired'
      end
    end
    resources :conflicts
    resources :pages
    match "balance_history" => "balance_history#index"
    post "orders/:id" => "orders#export"
  end

  namespace :writer do

    match "settings" => "writer#settings"
    match "save_mail_settings" => 'writer#save_mailer_settings'
    match "save_new_password" => 'writer#save_new_password'

    resources :items do
      get 'write'
      put 'written'
      get 'close'
      get 'delete'
      get 'refresh'
    end

    resources :payments do
      collection do
        get 'make'
      end
    end

    resources :orders do
      member do
        get 'write'
      end
    end

  end

end

app/views/admin/pages/_form.html.erb
<%= form_for [:admin, @page] do |f| %>
	<h4>Tytuł strony</h4>
	<p>
		<%= f.text_field :name %>
	</p>
	<h4>Kod w URL</h4>
	<p>
		<%= f.text_field :slug %>
	</p>
	<h4>Treść strony</h4>
	<p>
		<%= f.text_area :content, {:style => 'width: 100%; padding: 0; border: 0; height: 400px', :class => 'tinymce'} %>
		<%= tinymce %>
	</p>
	<p>
		<%= f.submit 'Zapisz', {:class => 'btn btn-primary'} %>
	</p>
<% end %>

app/views/admin/pages/edit.html.erb
	<%= render :partial => 'form' %><%= link_to 'Usuń', admin_page_path(@page), {:method => 'delete', :confirm => 'Czy jesteś pewien?', :class => 'btn btn-danger'} %>

app/views/admin/pages/index.html.erb
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Tytuł</th>
				<th></th>
			</tr>
		</thead>
		<tbody>	
		<% for page in @pages %>
			<tr>
				<td><%= page.id %></td>
				<td><%= link_to page.name, edit_admin_page_path(page) %></td>
				<td><%= link_to 'Usuń', admin_page_path(page), {:method => 'delete', :confirm => 'Czy jesteś pewien?', :class => 'btn btn-danger'} %></td>
			</tr>
		<% end %>
		</tbody>
	</table>

app/views/admin/pages/new.html.erb
<%= render :partial => 'form' %>