config/routes.rb
Textprovider::Application.routes.draw do
  devise_for :admins
  devise_for :users

  root :to => 'home#index'

  resources :orders
  resources :items
  resources :pages

  match 'p/:slug' => 'pages#show'

  namespace :admin do
    root :to => 'dashboard#index'
    match "customers" => 'admins#customers'
    match "profile" => 'admin#profile'
    match "mail_preferences" => 'admin#mail_settings'
    match "save_mail_preferences" => 'admin#save_mail_settings'
    put "update_password" => 'admin#update_password'
    resources :dashboard
    resources :users
    resources :payments do 
      member do
        get 'complete'
      end
    end
    resources :orders do
      member do
        get 'close'
      end
    end
    resources :admins
    resources :items do
      member do
        get 'confirm'
        get 'conflict'
      end
      collection do
        get 'expired'
        get 'set_expired'
      end
    end
    resources :conflicts
    resources :pages
    match "balance_history" => "balance_history#index"
    post "orders/:id" => "orders#export"
  end

  namespace :writer do

    match "settings" => "writer#settings"
    match "save_mail_settings" => 'writer#save_mailer_settings'
    match "save_new_password" => 'writer#save_new_password'

    resources :items do
      get 'write'
      put 'written'
      get 'close'
      get 'delete'
      get 'refresh'
    end

    resources :payments do
      collection do
        get 'make'
      end
    end

    resources :orders do
      member do
        get 'write'
      end
    end

  end

end

app/views/admin/_sidebar.html.erb
<% if current_admin.admin? %>
<ul class="nav nav-tabs nav-stacked">
	<li class="active"><a href="#">Użytkownicy</a></li>
	<li><%= link_to 'Lista', admin_users_path %></li>
	<li><%= link_to 'Wypłaty', admin_payments_path %></li>
</ul>
<% end %>

<ul class="nav nav-tabs nav-stacked">
	<li class="active"><a href="#">Teksty</a></li>
	<li><%= link_to 'Lista', admin_items_path %></li>
	<li><%= link_to 'Do zatwierdzenia', admin_items_path(:status => 5) %></li>
	<% if current_admin.admin? %>
	<li><%= link_to 'Wygasłe', expired_admin_items_path %></li>
	<% end %>
</ul>

<ul class="nav nav-tabs nav-stacked">
	<li class="active"><a href="#">Zlecenia</a></li>
	<li><%= link_to 'Lista', admin_orders_path %></li>
	<li><%= link_to 'Dodaj nowe', new_admin_order_path %></li>
</ul>

<% if current_admin.admin? %>
<ul class="nav nav-tabs nav-stacked">
	<li class="active"><a href="#">Strony</a></li>
	<li><%= link_to 'Lista', admin_pages_path %></li>
	<li><%= link_to 'Nowa strona', new_admin_page_path %></li>
</ul>
<% end %>

<% if current_admin.admin? %>
<ul class="nav nav-tabs nav-stacked">
	<li class="active"><a href="#">Klienci</a></li>
	<li><%= link_to 'Lista', admin_customers_path %></li>
</ul>
<% end %>

<ul class="nav nav-tabs nav-stacked">
	<li class="active"><a href="#">Finanse</a></li>
	<li><%= link_to 'Historia konta', admin_balance_history_path %></li>
</ul>