config/routes.rb
Textprovider::Application.routes.draw do
  devise_for :admins
  devise_for :users

  root :to => 'home#index'

  resources :orders
  resources :items
  resources :pages

  match 'p/:slug' => 'pages#show'

  namespace :admin do
    root :to => 'dashboard#index'
    match "customers" => 'admins#customers'
    match "profile" => 'admin#profile'
    match "mail_preferences" => 'admin#mail_settings'
    match "save_mail_preferences" => 'admin#save_mail_settings'
    put "update_password" => 'admin#update_password'
    resources :dashboard
    resources :users
    resources :payments do 
      member do
        get 'complete'
      end
    end
    resources :orders do
      member do
        get 'close'
      end
    end
    resources :admins
    resources :items do
      member do
        get 'confirm'
        get 'conflict'
      end
      collection do
        get 'expired'
        get 'set_expired'
      end
    end
    resources :conflicts
    resources :pages
    match "balance_history" => "balance_history#index"
    post "orders/:id" => "orders#export"
  end

  namespace :writer do

    match "settings" => "writer#settings"
    match "save_mail_settings" => 'writer#save_mailer_settings'
    match "save_new_password" => 'writer#save_new_password'

    resources :items do
      get 'write'
      put 'written'
      get 'close'
      get 'delete'
      get 'refresh'
    end

    resources :payments do
      collection do
        get 'make'
      end
    end

    resources :orders do
      member do
        get 'write'
      end
    end

  end

end

app/models/order.rb
# encoding: utf-8
class Order < ActiveRecord::Base
  attr_accessible :quantity, :user_id, :name, :signs, :description, :price, :ticket_time
  has_many :items, :dependent => :nullify
  belongs_to :admin
  
  default_scope order('created_at DESC')

  validates :ticket_time, :presence => true
  validates :quantity, :presence => true
  validates :quantity, :presence => true
  validates :price, :numericality => {:only_integer => true, :greater_than => -1}
  validates :quantity, :numericality => {:only_integer => true, :greater_than => -1}
  validates :name, :length => { :in => 14..200 }
  validates :ticket_time, :numericality => {:only_integer => true, :greater_than => 1799}

  def formal_name
   	self[:name] + ' (numer: #' + self[:id].to_s + ')'
	end

	def normalized_price
		price = (self[:price].to_f / 100)
		("%.2f" % price) + ' PLN'
	end

	def price_per_signs
		price = (self[:price].to_f / 100)
		price = price * (1000.0 / self[:signs].to_i)
		("%.2f" % price) + ' PLN / 1000 znaków'
	end

	def creator
		Admin.find(self[:admin_id])
	end

	def completed_items
		Item.where( :order_id => self[:id], :status => 10 )
	end

end

app/controllers/admin/orders_controller.rb
# coding: utf-8
class Admin::OrdersController < Admin::AdminController

	def send_new_order_notifications(order)
		@users = User.where( :notify_new_order => true )
		for user in @users
			UserMailer.new_order(user,order).deliver
		end
	end

	def index
		if current_admin.admin?
			@orders = Order.all
		else
			@orders = current_admin.orders
		end
	end

	def new
		@order = Order.new
	end

	def create
		@order = Order.new(params[:order])
		@order.admin_id = current_admin.id
		if @order.save
			#send_new_order_notifications(@order)
			redirect_to admin_orders_path
		else
			flash[:alert] = @order.errors.inspect
			render :new
		end
	end

	def show
		if current_admin.admin?
			@order = Order.find(params[:id])
		else
			@order = current_admin.orders.find(params[:id])
		end
	end

	def edit
		if current_admin.admin?
			@order = Order.find(params[:id])
		else
			@order = current_admin.orders.find(params[:id])
		end
	end

	def update
		if current_admin.admin?
			@order = Order.find(params[:id])
		else
			@order = current_admin.orders.find(params[:id])
		end
		if @order.update_attributes(params[:order])
			flash[:notice] = "Zlecenie zostało zmodyfikowane"
			redirect_to admin_order_path(@order)
		else
			flash[:alert] = @order.errors.messages.inspect
			render :edit
		end
	end

	def export
		@items = []
		for key,value in params[:item]
			@item = Item.find(key)
			if @item.order.admin = current_admin
				@export_item = @item.content
				@items.push( { :date => @item.updated_at, :content => @export_item } )
			end
		end
		render :xml => @items
	end

	def close
		if current_admin.admin?
			@order = Order.find(params[:id])
		else
			@order = current_admin.orders.find(params[:id])
		end
		@order.quantity = 0
		@order.save
		flash[:notice] = "Zlecenie zostało zakończone"
		redirect_to admin_order_path(@order)
	end

end

app/controllers/orders_controller.rb
# encoding: utf-8
class OrdersController < ApplicationController


	##
	# Lista aktywnych zleceń na teksty. 
	# params[:q] zawiera dane wyszukiwania (patrz gem ransack)
	def index
		begin
			if params[:q][:price_gteq].to_f > 0
				params[:q][:price_gteq] = params[:q][:price_gteq].to_f * 100
			end
			if params[:q][:price_lteq].to_f > 0
				params[:q][:price_lteq] = params[:q][:price_lteq].to_f * 100
			end
		rescue

		end
		@q = Order.where('quantity > 0').search(params[:q])
		@orders = @q.result

		for condition in @q.conditions
			if condition.attributes.first.name == 'price'
				condition.values.first.value = condition.values.first.value/100
			end
		end

	end

	##
	# Widok pojedynczego tekstu
	def show
		@order = Order.find(params[:id])
		@q = Order.where('quantity > 0').search(params[:q])
	end

end

app/controllers/writer/orders_controller.rb
# encoding: utf-8
class Writer::OrdersController < Writer::WriterController
	
	def write 
	# this method was used to 'Write' button on order#show

		# if current user has an active ticket for this order, redirect to existing ticket
		already_exists = Item.where(
			:user_id => current_user.id, 
			:order_id => params[:id],
			:status => 0 #means that this is a fresh text
		)
		already_exists.inspect
		unless already_exists.empty?
			redirect_to writer_item_write_path already_exists.first
			return #extremely important !
		end

		# unless, check if there are some free tickets
		@order = Order.find(params[:id])
		if @order.quantity > 0

			# tickets count - 1
			@order.quantity = @order.quantity - 1
			unless @order.valid?
				flash[:alert] = 'Wystąpił błąd'
				redirect_to order_path(@order)
				return
			end	
			@order.save

			# new item for this order and current user
			i = Item.new
			i.order_id = @order.id
			i.user_id = current_user.id
			i.status = 0
			i.price = @order.price
			i.expires = DateTime.current + @order.ticket_time.to_i.seconds
			i.save
			redirect_to writer_item_write_path(i)
			return #extremely important !

		end

		# there are no tickets left	
		redirect_to orders_path, :notice => "Przepraszamy, to zlecenie już się zakończyło."
		return

	end

end

app/views/admin/orders/_form.html.erb
	<%= form_for [:admin, @order] do |f| %>

		<h4>Tytuł zlecenia</h4>
		<p><%= f.text_field :name %></p>

		<h4>Opis zlecenia</h4>
		<p style="border-radius: 4px; border: 1px solid #ccc; padding: 10px;"><%= f.text_area :description, {:style => 'width: 100%; padding: 0; border: 0; height: 200px'} %></p>

		<h4>Wynagrodzenie [gr]</h4>
		<p><%= f.text_field :price %></p>

		<h4>Ilość znaków</h4>
		<p><%= f.text_field :signs %></p>

		<h4>Ilość tekstów</h4>
		<p><%= f.text_field :quantity %></p>

		<h4>Czas trwania ticketu [s] (minimum 1800 s - 30 minut)</h4>
		<p><%= f.text_field :ticket_time %></p>

		<p><%= f.submit "Zapisz", {:class => 'btn btn-primary'} %></p>
	<% end %>

app/views/admin/orders/edit.html.erb
<%= render :partial => 'form' %>

app/views/admin/orders/index.html.erb
	<%= render 'layouts/notifications' %>
	<table class="table">
		<thead>
			<th>Nazwa</th>
			<th>Dostępne</th>
			<th>Wynagrodzenie</th>
			<% if current_admin.admin? %>
				<th>Twórca</th>
			<% end %>
			<th></th>
		</thead>
		<tbody>
		<% @orders.each do |o| %>
			<tr>
				<td><%= link_to o.name, admin_order_path(o) %></td>
				<td><%= o.quantity %></td>
				<td><%= o.normalized_price %> <small>(<%= o.price_per_signs %>)</small></td>
				<% if current_admin.admin? %>
					<td><%= o.creator.email %></td>
				<% end %>
				<td>
					<%= link_to "Edytuj", edit_admin_order_path(o), {:class => 'btn btn-mini btn-warning'} %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>	

app/views/admin/orders/new.html.erb
<%= render :partial => 'form' %>

app/views/admin/orders/show.html.haml
%h2
	= @order.name
	%small
		pozostało tekstów:
		= @order.quantity
%p
	= link_to "Edytuj", edit_admin_order_path(@order), {:class => 'btn btn-warning'}
	- if @order.quantity > 0
		= link_to "Zakończ", close_admin_order_path(@order), {:class => 'btn btn-info', :confirm => "Jesteś pewien?"}

%h4 Wynagrodzenie
%p
	= @order.normalized_price
	%small= @order.price_per_signs

- if current_admin.admin?
	%h4 Twórca
	%p= @order.creator.email

%h4 Opis
%div.well= @order.description

%h4 Teksty
= form_tag admin_order_path(@order.id) do |f|
	%table.table
		%thead
			%tr
				%th{ :style => "width: 20px;"}
				%th Data
				%th
		%tbody
			- for item in @order.completed_items
				%tr
					%td
						%input{ :type => "checkbox", :name => "item[#{item.id}]", :checked => "checked" }
					%td= item.created_at
					%td= link_to 'Zobacz tekst', admin_item_path(item)
	%p				
		%input{:class => 'btn btn-submit', :value => "Eksportuj", :type => "submit"}