config/routes.rb
Textprovider::Application.routes.draw do
  devise_for :admins
  devise_for :users

  root :to => 'home#index'

  resources :orders
  resources :items
  resources :pages

  match 'p/:slug' => 'pages#show'

  namespace :admin do
    root :to => 'dashboard#index'
    match "customers" => 'admins#customers'
    match "profile" => 'admin#profile'
    match "mail_preferences" => 'admin#mail_settings'
    match "save_mail_preferences" => 'admin#save_mail_settings'
    put "update_password" => 'admin#update_password'
    resources :dashboard
    resources :users
    resources :payments do 
      member do
        get 'complete'
      end
    end
    resources :orders do
      member do
        get 'close'
      end
    end
    resources :admins
    resources :items do
      member do
        get 'confirm'
        get 'conflict'
      end
      collection do
        get 'expired'
        get 'set_expired'
      end
    end
    resources :conflicts
    resources :pages
    match "balance_history" => "balance_history#index"
    post "orders/:id" => "orders#export"
  end

  namespace :writer do

    match "settings" => "writer#settings"
    match "save_mail_settings" => 'writer#save_mailer_settings'
    match "save_new_password" => 'writer#save_new_password'

    resources :items do
      get 'write'
      put 'written'
      get 'close'
      get 'delete'
      get 'refresh'
    end

    resources :payments do
      collection do
        get 'make'
      end
    end

    resources :orders do
      member do
        get 'write'
      end
    end

  end

end

app/models/item.rb
# encoding: utf-8
##
# Klasa reprezentuje tekst realizowany przez wykonawcę, przypisany do zlecenia.
# Parametry:
#   user - użytkownik, wykonawca tekstu
#   order - zlecenie do którego należy tekst
class Item < ActiveRecord::Base

  include ActionView::Helpers::DateHelper

  attr_accessible :content, :order_id, :user_id

  belongs_to :order
  belongs_to :user
  has_many :conflicts, :dependent => :destroy

  default_scope order('created_at DESC')

  validates :order_id, :presence => true
  validates :user_id, :presence => true
  validates :status, :presence => true
  validates :price, :presence => true
  validates :expires, :presence => true

  def time_left
  	left = self[:expires].to_datetime - DateTime.current
  	left = left * 1.days
  	if left > 10
  		return '<span class="timer-countdown">' + left.to_i.to_s + '</span>'
  	else
  		return 'czas minął'
  	end

  end

  def formal_name
  	'numer: #' + self[:id].to_s
  end

  def status_name
  	case self[:status].to_i
  		when 0
  			'<span class="label">Otwarte</span>'
      when 3
        '<span class="label label-important">Odrzucone</span>'
  		when 5
  			'<span class="label label-info">Zamknięte, oczekuje na potwierdzenie</span>'
  		when 8
  			'<span class="label label-important">Czas minął</span>'
      when 10
        '<span class="label label-success">Zatwierdzone</span>'
  	end

  # status legend:
  # 0 - open, after created
  # 3 - get back from status 5 becouse of alert ser by admin
  # 5 - saved and waiting for check
  # 8 - saved after time has gone
  # 10 - confirmed, account balance increased
	end

  def expired_icon
    if (self[:expires] - DateTime.current) < 0 and self[:status] == 0
      '<span class="label label-important">Czas minął</span>'
    else
      return ''
    end
  end

	def normalized_price
		price = (self[:price].to_f / 100)
		("%.2f" % price) + ' PLN'
	end

  def expired_time_label   
    unless status == 0
      return ''
    end 
    if( self[:expires] - DateTime.current) < 0
      "<span class='label label-important'>#{distance_of_time_in_words_to_now(expires)}</span>"
    else
      "<span class='label label-info'>#{distance_of_time_in_words_to_now(expires)}</span>"
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::AdminController

	def index
		if current_admin.admin?
			if params[:status].nil?
				@items = Item.all
			else
				@items = Item.where( :status => params[:status])
			end
		else
			if params[:status].nil?
				@items = Item.joins(:order).where("orders.admin_id = #{current_admin.id}")
			else
				@items = Item.joins(:order).where("orders.admin_id = #{current_admin.id} and status = #{params[:status]}")
			end
		end
	end

	def expired
		if current_admin.admin?
			@items = Item.where(:status => 0).where("expires < '#{DateTime.current}'")
		end
	end

	def set_expired
		if current_admin.admin?
			@items = Item.where(:status => 0).where("expires < '#{DateTime.current}'")
			for item in @items
				item.order.quantity += 1
				item.status = 8
				item.save
				item.order.save
			end
			redirect_to expired_admin_items_path
		end
	end

	def show
		@item = Item.find(params[:id])
		unless current_admin.admin?
			if @item.order.admin != current_admin
				raise ActionController::RoutingError.new('Not Found')
			end
		end
	end

	def confirm
		# find item
		@item = Item.where(
			:id => params[:id],
			:status => 5
		).first
		# do not allow access for those customers who dont own this item
		unless current_admin.admin?
			if @item.order.admin != current_admin
				raise ActionController::RoutingError.new('Not Found')
			end
		end
		# set as confirmed and save
		@item.status = 10
		@item.save!
		# save user balance
		@item.user.balance += @item.price
		@item.user.save!
		# create balance history record
		@balance_history = BalanceHistory.new
		@balance_history.item = @item
		@balance_history.admin = @item.order.admin
		@balance_history.user = @item.user
		@balance_history.value = (@item.price * -1)
		@balance_history.comment = "Realizacja tekstu do zlecenia ID #{@item.order.id}"
		@balance_history.save!
		# save new admin balance
		admin = @balance_history.admin
		admin.balance -= @item.price
		admin.save!


		redirect_to admin_item_path(@item)
	end

	def conflict
		@item = Item.where(
			:id => params[:id],
			:status => 5
		).first
		unless current_admin.admin?
			if @item.order.admin != current_admin
				raise ActionController::RoutingError.new('Not Found')
			end
		end
		@conflict = @item.conflicts.new
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

end

app/controllers/writer/items_controller.rb
class Writer::ItemsController < Writer::WriterController

	def index
		if params[:s] != nil
			@items = current_user.items.where(:status => params[:s])
		else
			@items = current_user.items
		end
	end

	def show
		@item = current_user.items.find(params[:id])
	end

	def write
		@item = current_user.items.where(
			:id => params[:item_id],
			:status => 0
		).first()
	end

	def written
		@item = current_user.items.where(
			:id => params[:item_id],
			:status => 0
		).first()
		@item.content = params[:item][:content]
		@item.save
		redirect_to writer_item_path(@item)
	end

	def close
		@item = current_user.items.where(
			:id => params[:item_id],
			:status => 0
		).first()
		# check if there is still time for this
		if @item.expires < DateTime.current
			@item.status = 8
			@item.save
			@item.order.quantity = @item.order.quantity + 1
			@item.order.save
		else
			@item.status = 5
		end
		@item.save
		redirect_to writer_item_path(@item)
	end

	def delete
		@item = current_user.items.where(
			:id => params[:item_id],
			:status => 0
		).first
		@item.destroy
		redirect_to writer_items_path
	end

	def refresh
		@item = current_user.items.where(
			:id => params[:item_id],
			:status => 8
		).first
		if @item.order.quantity > 0
			@item.order.quantity = @item.order.quantity - 1
			unless @item.order.valid?
				redirect_to order_path(@item.order)
				return
			end
			@item.order.save
			@item.status = 0
			@item.price = @item.order.price
			@item.expires = DateTime.current + @item.order.ticket_time.to_i.seconds
			@item.save
		end
		redirect_to writer_item_path(@item)
	end

end

app/controllers/writer/orders_controller.rb
# encoding: utf-8
class Writer::OrdersController < Writer::WriterController
	
	def write 
	# this method was used to 'Write' button on order#show

		# if current user has an active ticket for this order, redirect to existing ticket
		already_exists = Item.where(
			:user_id => current_user.id, 
			:order_id => params[:id],
			:status => 0 #means that this is a fresh text
		)
		already_exists.inspect
		unless already_exists.empty?
			redirect_to writer_item_write_path already_exists.first
			return #extremely important !
		end

		# unless, check if there are some free tickets
		@order = Order.find(params[:id])
		if @order.quantity > 0

			# tickets count - 1
			@order.quantity = @order.quantity - 1
			unless @order.valid?
				flash[:alert] = 'Wystąpił błąd'
				redirect_to order_path(@order)
				return
			end	
			@order.save

			# new item for this order and current user
			i = Item.new
			i.order_id = @order.id
			i.user_id = current_user.id
			i.status = 0
			i.price = @order.price
			i.expires = DateTime.current + @order.ticket_time.to_i.seconds
			i.save
			redirect_to writer_item_write_path(i)
			return #extremely important !

		end

		# there are no tickets left	
		redirect_to orders_path, :notice => "Przepraszamy, to zlecenie już się zakończyło."
		return

	end

end

app/controllers/writer/payments_controller.rb
# encoding: utf-8
class Writer::PaymentsController < Writer::WriterController

	def index
		@balance_history = BalanceHistory.where( :user_id => current_user.id )
	end

	def make
		@payment = Payment.new
		@payment.value = current_user.balance
	end

	def create
		@payment = Payment.new
		@payment.value = params[:payment][:value]
		@payment.user = current_user
		@payment.status = Payment::Request
		if current_user.balance >= @payment.value
			current_user.balance -= @payment.value
			current_user.save!
			@payment.save!
			balance_history = BalanceHistory.new
			balance_history.payment = @payment
			balance_history.user = current_user
			balance_history.value = @payment.value
			balance_history.comment = "Zlecenie wypłaty ##{@payment.id}"
			balance_history.save!
			flash[:notice] = "Wypłata została zlecona"
			redirect_to writer_payments_path
			return
		else
			flash[:notice] = "Brak wystarczających środków"
			redirect_to writer_payments_path
			return
		end
	end

end	

app/controllers/writer/writer_controller.rb
# encoding: utf-8
class Writer::WriterController < ApplicationController

	before_filter :authenticate_user!

	def settings
		@user = current_user
		@tab = params[:tab]
	end

	def save_mailer_settings
		@user = current_user
		# new order mailer
		begin
			if params[:mailer][:new_order]
				@user.notify_new_order = true
			else
				@user.notify_new_order = false
			end
		rescue
			@user.notify_new_order = false
		end
		# item accept
		begin
			if params[:mailer][:item_accept]
				@user.notify_item_accept = true
			else
				@user.notify_item_accept = false
			end
		rescue
			@user.notify_item_accept = false
		end

		# item reject
		begin
			if params[:mailer][:item_reject]
				@user.notify_item_reject = true
			else
				@user.notify_item_reject = false
			end
		rescue
			@user.notify_item_reject = false
		end

		@user.save
		flash[:notice] = "Ustawienia zostały zapisane"
		redirect_to writer_settings_path({:tab => 'mail'})
	end

	def save_new_password
		@user = current_user
	    if @user.update_attributes(params[:admin])
	      	sign_in @user, :bypass => true
	      	flash[:notice] = "Hasło zostało zmienione"
	      	redirect_to writer_settings_path
	    else
	    	flash[:alert] = "Wystąpił błąd"
	    	render :profile
	    end
	end

end

app/views/writer/items/index.html.erb
<div class="span2">
  <%= render :partial => 'sidebar' %>
</div>
<div class="span10">
	<%= render 'layouts/notifications' %>
	<ul class="breadcrumb">
	  <li><%= link_to 'Home', root_path %> <span class="divider">/</span></li>
	  <li class="active">Teksty</li>
	</ul>

	<table class="table">
		<thead>
			<th>ID</th>
			<th>Nazwa</th>
			<th>Status</th>
			<th>Wynagrodzenie</th>
		</thead>
		<tbody>
		<% @items.each do |i| %>
			<tr>
				<td>#<%= i.order.id %>/#<%= i.id %></td>
				<td><%= link_to i.order.name, writer_item_path(i) %></td>
				<td><%= i.status_name.html_safe %></td>
				<td><%= i.normalized_price %></td>
			</tr>
		<% end %>
		</tbody>
	</table>	
</div>

app/views/writer/items/show.html.erb
<div class="span2">
  <%= render :partial => 'sidebar' %>
</div>

<div class="span10">
  
  <%= render 'layouts/notifications' %>

		<ul class="breadcrumb">
		  <li><%= link_to 'Home', root_path %> <span class="divider">/</span></li>
		  <li><%= link_to 'Teksty', writer_items_path %> <span class="divider">/</span></li>
		  <li class="active">Mój tekst (<%= @item.formal_name %>)</li>
		</ul>

		<h1>
			<%= @item.order.name %>
		</h1>

		<% if @item.status == 0 %>
			<p>Pozostały czas: <%= @item.time_left.html_safe %></p>
		<% end %>

		<hr />

		<p>
			<%= @item.content %>
		</p>

		<hr />

		<p><strong>Przychód:</strong> <%= @item.normalized_price %></p>

		<p><strong>Status:</strong> <%= @item.status_name.html_safe %></p>
		<% if @item.status == 0 %>
		<p>
			<%= link_to 'Edytuj', writer_item_write_path(@item), {:class => 'btn btn-warning'} %>
			<%= link_to 'Wyślij', writer_item_close_path(@item), {:class => 'btn btn-primary'} %>
			<%= link_to 'Usuń', writer_item_delete_path(@item), {:class => 'btn btn-danger'}, :confirm => 'Jesteś pewien?' %>
		</p>
		<% end %>

		<% if @item.status == 8 and @item.order.quantity > 0 %>
			<p>Pomimo tego, że czas na realizację przyznanego Ci tekstu dobiegł końca, to zlecenie jest nadal otwarte i możesz dokończyć pracę.</p>
			<%= link_to 'Dokończ tekst', writer_item_refresh_path(@item), {:class => 'btn btn-primary'} %> 
		<% end %>

		<% if @item.status == 8 and @item.order.quantity == 0 %>
			<p>Zlecenie już się zakończyło.</p>
		<% end %>

		<% unless @item.conflicts.empty? %>
		<hr />
		<h3>Komentarze</h3>
	<% end %>

	<% for element in @item.conflicts %>
		<p>
			<% if element.author == current_user %>
				<strong><%= element.author.email %></strong>
			<% else %>
				<strong>Administracja</strong>
			<% end %>
			<small>	
				<%= distance_of_time_in_words_to_now(element.updated_at.to_time,) %> ago
			</small>
		<p>
		<div class='well well-small'><%= element.content %></div>
		<hr />
	<% end %>

</div>

app/views/writer/items/write.html.erb
<div class="span2">
	<%= render :partial => 'sidebar' %>
</div>
<div class="span10">
  
  <%= render 'layouts/notifications' %>



		<ul class="breadcrumb">
		  <li><%= link_to 'Home', root_path %> <span class="divider">/</span></li>
		  <li><%= link_to 'Zlecenia', orders_path %> <span class="divider">/</span></li>
		  <li><%= link_to @item.order.formal_name, order_path(@item.order) %> <span class="divider">/</span></li>
		  <li class="active">Realizacja zlecenia</li>
		</ul>

		<h1>
			<%= @item.order.name %>
		</h1>

		<p>Pozostały czas: <%= @item.time_left.html_safe %></p>
		
		<%= form_for @item, :url => {:action => 'written'} do |f| %>
			<div style="border: 1px solid #ccc; border-radius: 5px; margin-bottom: 20px; margin-top: 10px; padding: 10px;">
		  	<%= f.text_area :content, {:style => 'width: 100%; padding: 0; border:0; margin: 0; height: 300px;', :id => 'main-item-textarea'} %>
		  </div>
		  <%= f.submit "Zapisz", {:class => 'btn btn-primary'} %>
		<% end %>
		<p>Ilość znaków: <span id="letter-counter"></span></p>

		<script type="text/javascript">
		$(document).ready( function(){
			$('#main-item-textarea').keyup( function() {
				$('#letter-counter').html($(this).val().length)
			})
		})
		</script>

</div>